spring.application.name=staysarthi-backend

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=staysarthi

server.port=${PORT:8080}
server.address=0.0.0.0

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
